"use client";

import { useMemo, useState } from "react";
import { Eye, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { leadStatuses } from "@/lib/site-config";

type Lead = { id: number; createdAt: string; name: string; businessName: string; email: string; phone: string; website: string; service: string; packageName: string; message: string; status: string; source: string; priority: string; estimatedValue: number | null; notes: string; utmSource: string; utmMedium: string; utmCampaign: string; updatedAt: string; utmContent: string; utmTerm: string };

export function AdminLeadsTable({ initialRows }: { initialRows: Lead[] }) {
  const [rows, setRows] = useState(initialRows); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("ALL");
  const visible = useMemo(() => rows.filter((row) => (filter === "ALL" || row.status === filter) && `${row.name} ${row.businessName} ${row.email} ${row.service}`.toLowerCase().includes(query.toLowerCase())), [rows, query, filter]);
  async function remove(id: number) { const response = await fetch(`/api/admin/leads/${id}`, { method: "DELETE" }); if (response.ok) setRows((current) => current.filter((row) => row.id !== id)); }
  return <section><div className="admin-filters"><div className="admin-search"><Search /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, business, email or service" /></div><Select value={filter} onValueChange={(value) => setFilter(value ?? "ALL")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">All statuses</SelectItem>{leadStatuses.map((status) => <SelectItem key={status} value={status}>{status.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div>
    <div className="admin-table-wrap"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Name</TableHead><TableHead>Business</TableHead><TableHead>Email</TableHead><TableHead>Service</TableHead><TableHead>Package</TableHead><TableHead>Status</TableHead><TableHead>Source</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{visible.map((row) => <TableRow key={row.id}><TableCell>{new Date(row.createdAt).toLocaleDateString("en-GB")}</TableCell><TableCell>{row.name}</TableCell><TableCell>{row.businessName}</TableCell><TableCell><a href={`mailto:${row.email}`}>{row.email}</a></TableCell><TableCell>{row.service || "-"}</TableCell><TableCell>{row.packageName || "-"}</TableCell><TableCell><span className={`status-pill status-${row.status.toLowerCase()}`}>{row.status.replaceAll("_", " ")}</span></TableCell><TableCell>{row.utmSource || row.source}</TableCell><TableCell><div className="table-actions"><LeadSheet row={row} onUpdate={(updated) => setRows((current) => current.map((item) => item.id === updated.id ? updated : item))} /><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`Delete ${row.businessName}`}><Trash2 /></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this lead?</AlertDialogTitle><AlertDialogDescription>This permanently removes {row.businessName} from the database.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={() => remove(row.id)}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></TableCell></TableRow>)}</TableBody></Table>{visible.length === 0 && <p className="empty-table">No leads match the current filters.</p>}</div>
  </section>;
}

function LeadSheet({ row, onUpdate }: { row: Lead; onUpdate: (lead: Lead) => void }) {
  const [status, setStatus] = useState(row.status); const [priority, setPriority] = useState(row.priority); const [notes, setNotes] = useState(row.notes); const [estimatedValue, setEstimatedValue] = useState(row.estimatedValue?.toString() ?? ""); const [saving, setSaving] = useState(false);
  async function save() { setSaving(true); const response = await fetch(`/api/admin/leads/${row.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, priority, notes, estimatedValue: estimatedValue ? Number(estimatedValue) : null }) }); const result = await response.json() as { lead?: Lead }; if (response.ok && result.lead) onUpdate(result.lead); setSaving(false); }
  return <Sheet><SheetTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`View ${row.businessName}`}><Eye /></Button></SheetTrigger><SheetContent className="admin-detail-sheet"><SheetHeader><SheetTitle>{row.businessName}</SheetTitle><SheetDescription>{row.name} · {row.email}</SheetDescription></SheetHeader><div className="admin-detail-body"><div className="detail-pairs"><div><span>Phone</span><a href={`tel:${row.phone}`}>{row.phone || "Not supplied"}</a></div><div><span>Website</span><a href={row.website || undefined}>{row.website || "Not supplied"}</a></div><div><span>Service</span><strong>{row.service || "Not specified"}</strong></div><div><span>Package</span><strong>{row.packageName || "Not specified"}</strong></div></div><div className="detail-message"><span>Message</span><p>{row.message}</p></div><div className="form-field"><Label>Status</Label><Select value={status} onValueChange={(value) => setStatus(value ?? status)}><SelectTrigger className="found-select"><SelectValue /></SelectTrigger><SelectContent>{leadStatuses.map((item) => <SelectItem key={item} value={item}>{item.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="form-field"><Label>Priority</Label><Select value={priority} onValueChange={(value) => setPriority(value ?? priority)}><SelectTrigger className="found-select"><SelectValue /></SelectTrigger><SelectContent>{["HOT","WARM","COLD"].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="form-field"><Label htmlFor={`value-${row.id}`}>Estimated value</Label><Input id={`value-${row.id}`} type="number" min="0" step="10" value={estimatedValue} onChange={(event) => setEstimatedValue(event.target.value)} /></div><div className="form-field"><Label htmlFor={`notes-${row.id}`}>Internal notes</Label><Textarea id={`notes-${row.id}`} rows={6} value={notes} onChange={(event) => setNotes(event.target.value)} /></div><Button onClick={save} disabled={saving}>{saving ? "Saving..." : "Save changes"}</Button></div></SheetContent></Sheet>;
}
