import {
  BarChart3,
  Bot,
  Building2,
  Crosshair,
  Globe2,
  MapPin,
  Search,
  ShieldCheck,
} from "lucide-react";

export const services = [
  {
    slug: "web-design",
    title: "Premium Websites",
    short: "A modern website built around the actions that matter: calls, bookings and enquiries.",
    icon: Globe2,
    eyebrow: "Design & development",
    headline: "A website built to earn attention and turn it into business.",
    intro:
      "We combine strategy, UX, sharp visual design and reliable development into a fast, clear website that makes your business feel established from the first click.",
    benefits: [
      "Business and competitor discovery",
      "Customer journey and conversion strategy",
      "Premium responsive design",
      "Fast, secure development and deployment",
      "WhatsApp, click-to-call and booking journeys",
      "Google Maps and contact integrations",
      "Copywriting guidance and content structure",
      "Analytics, Search Console and SEO foundations",
      "Launch support and an ongoing care plan",
    ],
    result: "A professional digital home that is easy to trust, easy to use and ready to grow.",
  },
  {
    slug: "local-seo",
    title: "Local SEO",
    short: "Build the relevance, structure and authority needed to compete in local search.",
    icon: Search,
    eyebrow: "Organic visibility",
    headline: "Be present when local customers are actively searching.",
    intro:
      "Local SEO connects your services to the searches people make in Nicosia, Limassol, Larnaca, Paphos and across Cyprus. We build a sound foundation and improve it over time.",
    benefits: [
      "Local keyword and competitor research",
      "Service and location content planning",
      "Technical SEO and metadata",
      "Structured data and internal linking",
      "Search Console configuration",
      "Indexing and visibility checks",
      "Ongoing content and SEO optimisation",
      "Clear reporting tied to enquiries",
    ],
    result: "Stronger search visibility without unrealistic promises or guaranteed rankings.",
  },
  {
    slug: "google-business",
    title: "Google Business",
    short: "Turn your profile into a complete, credible entry point for local customers.",
    icon: MapPin,
    eyebrow: "Local presence",
    headline: "Make the most important local search result work harder.",
    intro:
      "We audit and refine your Google Business Profile so customers can quickly understand what you do, where you operate and how to take the next step.",
    benefits: [
      "Primary and secondary category optimisation",
      "Accurate business information and opening hours",
      "Services, descriptions and website links",
      "Profile completeness review",
      "Photo and content recommendations",
      "Ethical review request strategy",
      "Local visibility and website alignment",
    ],
    result: "A clearer, more complete profile that supports discovery and trust.",
  },
  {
    slug: "maintenance",
    title: "Website Maintenance",
    short: "Hosting, monitoring, backups and practical support after launch.",
    icon: ShieldCheck,
    eyebrow: "Ongoing care",
    headline: "Your website should stay fast, secure and up to date.",
    intro:
      "Launch is the beginning. Our care plans keep the technical foundation healthy and give you a reliable place to send small monthly updates.",
    benefits: [
      "Managed hosting, SSL and backups",
      "Security and uptime monitoring",
      "Technical and dependency updates",
      "Form and performance checks",
      "Analytics health checks",
      "Text, image, contact detail and opening-hour changes",
      "Practical support when something needs attention",
    ],
    result:
      "Minor updates cover small content changes. New pages, systems, integrations and redesign work are quoted separately, and unused time does not roll over.",
  },
  {
    slug: "analytics",
    title: "Analytics & Tracking",
    short: "Measure calls, messages, bookings and form submissions, not just traffic.",
    icon: BarChart3,
    eyebrow: "Measurement",
    headline: "Visitors are useful. Actions are more useful.",
    intro:
      "We configure privacy-aware analytics around the actions that show commercial intent, giving you a clearer view of what generates interest.",
    benefits: [
      "Phone and WhatsApp click tracking",
      "Email and booking click tracking",
      "Contact and audit form submissions",
      "Pricing and service engagement",
      "Google Analytics 4 configuration",
      "Campaign and UTM attribution",
      "Conversion-focused reporting",
    ],
    result: "A measurement system that helps you make better marketing decisions.",
  },
  {
    slug: "automation",
    title: "Automation",
    short: "Connect enquiries, bookings and follow-up steps without overcomplicating the business.",
    icon: Bot,
    eyebrow: "Smarter workflows",
    headline: "Remove repetitive steps from the customer journey.",
    intro:
      "We design practical automations around clear business rules. The goal is faster response and fewer missed opportunities, not AI for its own sake.",
    benefits: [
      "AI website chatbots with defined boundaries",
      "Enquiry routing and lead notifications",
      "Booking and reminder automation",
      "CRM and internal system integrations",
      "Email follow-up workflows",
      "Forms connected to operational systems",
      "Human hand-off where judgement is needed",
    ],
    result: "A simpler, more consistent process for handling digital enquiries.",
  },
  {
    slug: "3d-virtual-tours",
    title: "3D Virtual Tours",
    short: "Interactive browser-based walkthroughs for properties and physical spaces.",
    icon: Building2,
    eyebrow: "Immersive presentation",
    headline: "Let people explore a space before they arrive.",
    intro:
      "For real estate, Airbnb, hospitality, developments and commercial spaces, we can plan a browser-based 3D experience using the capture workflow best suited to the project.",
    benefits: [
      "Project and location assessment",
      "Interactive browser-based walkthrough",
      "Website and listing integration",
      "Mobile and desktop viewing",
      "Matterport, Gaussian Splatting or modern capture options",
      "Optional property lead capture",
      "Hosting and presentation guidance",
    ],
    result: "A more immersive way to present a property, with technology selected after scoping.",
  },
  {
    slug: "conversion-optimisation",
    title: "Conversion Optimisation",
    short: "Clarify the journey so more visitors know exactly what to do next.",
    icon: Crosshair,
    eyebrow: "Better outcomes",
    headline: "Turn interest into a clear next step.",
    intro:
      "We review positioning, page flow, calls to action, mobile usability and friction points to help more of the right visitors contact your business.",
    benefits: [
      "Message and offer clarity",
      "Call-to-action strategy",
      "Mobile journey review",
      "Form friction reduction",
      "Trust and credibility signals",
      "Performance and analytics review",
    ],
    result: "A clearer journey from first impression to enquiry.",
  },
] as const;

export const projects = [
  {
    slug: "aura-dental",
    name: "AURA Dental",
    industry: "Dental Clinic",
    tone: "aura",
    statement: "Calm care. Clear choices.",
    problem: "An outdated dental website can make a modern clinic feel outdated.",
    concept: "A calm, premium and conversion-focused dental experience.",
    features: ["Appointment booking", "Treatment pages", "Doctors", "Reviews section", "Google Maps", "WhatsApp", "Click-to-call", "Gallery", "FAQ"],
  },
  {
    slug: "nova-estates",
    name: "NOVA Estates",
    industry: "Luxury Real Estate",
    tone: "nova",
    statement: "Cyprus properties, precisely presented.",
    problem: "Premium listings lose impact when search, imagery and enquiry journeys feel ordinary.",
    concept: "A dark editorial property platform with immersive detail and effortless lead capture.",
    features: ["Property listings", "Search and filters", "Property detail", "Gallery", "Agent profile", "WhatsApp", "Enquiry", "Map", "Virtual tour", "3D capability"],
  },
  {
    slug: "form-developments",
    name: "FORM Developments",
    industry: "Construction / Architecture",
    tone: "form",
    statement: "Built with purpose.",
    problem: "Strong work needs a digital presence with the same precision as the spaces being built.",
    concept: "An architectural portfolio defined by rhythm, material and confident restraint.",
    features: ["Project portfolio", "Case studies", "Services", "Capabilities", "Company profile", "Quote journey", "Project gallery", "Mobile-first layout"],
  },
] as const;

export const processSteps = [
  ["01", "Discover", "We understand the business, audience, competitors, services and goals."],
  ["02", "Strategy & Design", "We define the visual direction, message and customer journey."],
  ["03", "Build", "We develop the website, integrations, SEO and conversion tracking."],
  ["04", "Launch", "We complete QA, deployment, indexing and analytics checks."],
  ["05", "Grow", "We improve maintenance, SEO, automation, content and acquisition."],
] as const;
