import {
  BarChart3,
  Bot,
  Building2,
  Crosshair,
  Globe2,
  MapPin,
  Search,
  ShieldCheck,
} from "lucide-react";

export const services = [
  {
    slug: "web-design",
    title: "Premium Websites",
    short: "Modern websites designed and developed around the business goals that matter: enquiries, bookings, calls and sales.",
    icon: Globe2,
    eyebrow: "Design & development",
    headline: "A website built to earn attention and turn it into business.",
    intro:
      "We combine strategy, UX, sharp visual design and reliable development into a fast, clear website that makes your business feel established from the first click.",
    benefits: [
      "Business and competitor discovery",
      "Customer journey and conversion strategy",
      "Premium responsive design",
      "Fast, secure development and deployment",
      "WhatsApp, click-to-call and booking journeys",
      "Google Maps and contact integrations",
      "Copywriting guidance and content structure",
      "Analytics, Search Console and SEO foundations",
      "Launch support and an ongoing care plan",
    ],
    result: "A professional digital home that is easy to trust, easy to use and ready to grow.",
  },
  {
    slug: "local-seo",
    title: "Local SEO",
    short: "Strong local search foundations that help search engines understand the business, services and location.",
    icon: Search,
    eyebrow: "Organic visibility",
    headline: "Be present when local customers are actively searching.",
    intro:
      "Local SEO connects your services to the searches people make in Nicosia, Limassol, Larnaca, Paphos and across Cyprus. We build a strong search foundation with the structure your visibility can grow from over time.",
    benefits: [
      "Local keyword and competitor research",
      "Service and location content planning",
      "Technical SEO and metadata",
      "Structured data and internal linking",
      "Search Console configuration",
      "Indexing and visibility checks",
      "Post-launch search health checks",
      "Search performance tracking",
    ],
    result: "Stronger search visibility without unrealistic promises or guaranteed rankings.",
  },
  {
    slug: "google-business",
    title: "Google Business",
    short: "A complete and credible Google Business Profile that connects customers with the right information, website, services and actions.",
    icon: MapPin,
    eyebrow: "Local presence",
    headline: "Make the most important local search result work harder.",
    intro:
      "We audit and refine your Google Business Profile so customers can quickly understand what you do, where you operate and how to take the next step.",
    benefits: [
      "Primary and secondary category optimisation",
      "Accurate business information and opening hours",
      "Services, descriptions and website links",
      "Profile completeness review",
      "Photo and content recommendations",
      "Ethical review request strategy",
      "Local visibility and website alignment",
    ],
    result: "A clearer, more complete profile that supports discovery and trust.",
  },
  {
    slug: "website-care",
    title: "Website Care",
    short: "Hosting, monitoring, updates, backups and practical support after launch.",
    icon: ShieldCheck,
    eyebrow: "Ongoing care",
    headline: "Your website should stay fast, secure and up to date.",
    intro:
      "Launch is the beginning. Our care plans keep the technical foundation healthy and give you a reliable place to send small monthly updates.",
    benefits: [
      "Managed hosting, SSL and backups",
      "Security and uptime monitoring",
      "Technical and dependency updates",
      "Form and performance checks",
      "Analytics health checks",
      "Text, image, contact detail and opening-hour changes",
      "Practical support when something needs attention",
    ],
    result:
      "Minor updates cover small content changes. New pages, systems, integrations and redesign work are quoted separately, and unused time does not roll over.",
  },
  {
    slug: "analytics",
    title: "Analytics & Tracking",
    short: "Track visits, calls, messages, bookings, form submissions and other important customer actions.",
    icon: BarChart3,
    eyebrow: "Measurement",
    headline: "Visitors are useful. Actions are more useful.",
    intro:
      "We configure privacy-aware analytics around the actions that show commercial intent, giving you a clearer view of what generates interest.",
    benefits: [
      "Phone and WhatsApp click tracking",
      "Email and booking click tracking",
      "Contact and audit form submissions",
      "Pricing and service engagement",
      "Google Analytics 4 configuration",
      "Campaign and UTM attribution",
      "Conversion and engagement reporting",
    ],
    result: "A measurement system that helps you make better marketing decisions.",
  },
  {
    slug: "conversion-design",
    title: "Conversion-Focused Design",
    short: "Clear customer journeys built around trust and meaningful actions.",
    icon: Crosshair,
    eyebrow: "Clearer customer journeys",
    headline: "Make the next step obvious.",
    intro:
      "We shape page structure, content hierarchy and calls to action around how people decide to call, message, book, enquire or buy.",
    benefits: [
      "Message and offer clarity",
      "Clear call-to-action strategy",
      "Enquiry and booking paths",
      "WhatsApp and click-to-call actions",
      "Trust signals, reviews and reassurance",
      "Simplified forms and mobile usability",
      "Analytics-informed next steps",
    ],
    result: "A clearer route from first impression to the action that matters to the business.",
  },
] as const;

export const customCapabilities = [
  {
    slug: "automation",
    title: "Lead & Booking Automation",
    short: "Practical workflows added when a project genuinely benefits from them.",
    icon: Bot,
    eyebrow: "Custom capability",
    headline: "Useful workflows, where they make sense.",
    intro:
      "Automation is an optional layer for projects that need it, connecting simple business workflows without turning the website into an enterprise system.",
    benefits: [
      "Website form to email notification",
      "Enquiry to CRM webhook",
      "Booking confirmation flows",
      "Simple lead follow-up",
      "Newsletter signup to email platform",
      "Contact form to internal pipeline",
    ],
    result: "A practical workflow that removes a repetitive step while keeping the business in control.",
  },
  {
    slug: "3d-virtual-tours",
    title: "3D Virtual Tours",
    short: "Interactive browser-based walkthroughs for properties and physical spaces.",
    icon: Building2,
    eyebrow: "Immersive presentation",
    headline: "Let people explore a space before they arrive.",
    intro:
      "For real estate, Airbnb, hospitality, developments and commercial spaces, we can plan a browser-based 3D experience using the capture workflow best suited to the project.",
    benefits: [
      "Project and location assessment",
      "Interactive browser-based walkthrough",
      "Website and listing integration",
      "Mobile and desktop viewing",
      "Matterport, Gaussian Splatting or modern capture options",
      "Optional property lead capture",
      "Hosting and presentation guidance",
    ],
    result: "A more immersive way to present a property, with technology selected after scoping.",
  },
] as const;

export const legacyServiceAliases = {
  maintenance: "website-care",
  "conversion-optimisation": "conversion-design",
} as const;

export const archivedCapabilities = customCapabilities.filter(({ slug }) => slug === "3d-virtual-tours");

export const projects = [
  {
    slug: "aura-dental",
    image: "/images/work/aura-dental-cover.png",
    name: "AURA Dental",
    industry: "Dental Clinic",
    tone: "aura",
    statement: "Calm care. Clear choices.",
    problem: "An outdated dental website can make a modern clinic feel outdated.",
    concept: "A calm, premium and conversion-focused dental experience.",
    features: ["Appointment booking", "Treatment pages", "Doctors", "Reviews section", "Google Maps", "WhatsApp", "Click-to-call", "Gallery", "FAQ"],
  },
  {
    slug: "nova-estates",
    image: "/images/work/nova-estates-cover.png",
    name: "NOVA Estates",
    industry: "Luxury Real Estate",
    tone: "nova",
    statement: "Cyprus properties, precisely presented.",
    problem: "Premium listings lose impact when search, imagery and enquiry journeys feel ordinary.",
    concept: "A dark editorial property platform with immersive detail and effortless lead capture.",
    features: ["Property listings", "Search and filters", "Property detail", "Gallery", "Agent profile", "WhatsApp", "Enquiry", "Map", "Virtual tour", "3D capability"],
  },
  {
    slug: "form-developments",
    image: "/images/work/form-developments-cover.png",
    name: "FORM Developments",
    industry: "Construction / Architecture",
    tone: "form",
    statement: "Built with purpose.",
    problem: "Strong work needs a digital presence with the same precision as the spaces being built.",
    concept: "An architectural portfolio defined by rhythm, material and confident restraint.",
    features: ["Project portfolio", "Case studies", "Services", "Capabilities", "Company profile", "Quote journey", "Project gallery", "Mobile-first layout"],
  },
  {
    slug: "vela-studio",
    image: "/images/work/vela-studio-cover.png",
    name: "VELA Studio",
    industry: "Beauty / Wellness",
    tone: "vela",
    statement: "A quieter kind of confidence.",
    problem: "A beautiful studio can still lose appointments when services, availability and trust are hard to understand online.",
    concept: "A warm, appointment-led beauty experience that makes choosing a treatment feel calm and personal.",
    features: ["Service menu", "Appointment booking", "Team profiles", "Treatment gallery", "Reviews section", "WhatsApp", "Instagram integration", "Location and hours", "FAQ"],
  },
  {
    slug: "ora-jewellery",
    image: "/images/work/ora-jewellery-cover.png",
    name: "ORA Jewellery",
    industry: "Retail / E-commerce",
    tone: "ora",
    statement: "Wear the moment.",
    problem: "Product-led retail loses desire when collections, craftsmanship and the path to purchase feel disconnected.",
    concept: "A dark editorial jewellery store built around product storytelling, considered browsing and confident conversion.",
    features: ["Collections", "Product detail", "E-commerce journey", "Editorial stories", "Product filters", "Size and care guidance", "Wishlist", "Secure checkout", "Delivery information"],
  },
] as const;

export const processSteps = [
  ["01", "Discover", "We understand the business, audience, competitors, services and goals."],
  ["02", "Strategy & Design", "We define the visual direction, message and customer journey."],
  ["03", "Build", "We develop the website and implement the agreed integrations, SEO foundations and tracking."],
  ["04", "Launch", "We complete QA, deployment, indexing and analytics checks."],
  ["05", "Grow", "After launch, we support the website and improve SEO, analytics and other agreed areas as the business grows."],
] as const;
