export const faqs = [
  ["How much does a website cost?", "Our current packages start at €550 setup plus €49 per month for Website Care after launch. The right package depends on page count, integrations, content and the role the website plays in your business."],
  ["How long does a website take?", "A focused small business website usually takes a few weeks once content and feedback are supplied. More complex sites take longer. Your proposal will include a realistic schedule."],
  ["How do payments work?", "The standard process is 50% to begin and 50% before launch. Monthly care starts when the site goes live."],
  ["Will I own my website?", "Yes. Ownership and access are documented in the proposal. Any licensed third-party tools remain subject to their own terms."],
  ["Can you work with my current domain?", "Yes. We can connect an existing domain and help coordinate DNS changes without unnecessarily disrupting email or other services."],
  ["Do you provide hosting?", "Yes. Managed hosting, SSL, monitoring and backups are included in the Website Care shown with the pricing packages."],
  ["What does Website Care include?", "Website Care covers hosting, monitoring, technical updates, backups and the monthly allowance for minor text, image, contact-detail or opening-hour changes."],
  ["Does unused Website Care time roll over?", "No. Your monthly minor-update allowance is reserved for that month and does not roll over."],
  ["Do you guarantee first place on Google?", "No responsible provider can guarantee a ranking. We build a sound SEO foundation and improve relevance, quality and visibility over time."],
  ["Can you write the website content?", "All packages include content structure and guidance. Growth includes copywriting assistance. Full or specialist copywriting can be quoted separately."],
  ["What about photography and video?", "We can work with your existing assets, recommend a shoot or coordinate professional photography and videography as an add-on."],
  ["How many revisions are included?", "The proposal defines clear feedback stages. We aim to align direction early so revisions remain focused and productive."],
  ["Can the website be in Greek and English?", "Premium includes a multilingual-ready architecture. Translation, content entry and complete second-language setup can be scoped separately."],
  ["Will I see calls and enquiries in analytics?", "Yes. Where consent and technology allow, we track meaningful actions such as phone, WhatsApp, email, booking and form interactions."],
  ["Can you connect a booking system?", "Yes. We can connect an existing booking platform or scope a more advanced booking workflow as an add-on."],
  ["Can you redesign my existing website?", "Yes. We can audit the current site, retain what is useful and rebuild the experience around clearer goals."],
  ["Do you build e-commerce websites?", "E-commerce can be scoped separately. The packages shown focus on lead-generating local business websites."],
  ["What happens after launch?", "Website Care covers the agreed hosting, technical care and minor updates. Ongoing SEO, Google Business optimisation, advanced analytics, advertising, automation, content and integrations can be scoped separately when useful."],
  ["Can FOUND. help with digital growth after the website launches?", "Yes. Depending on what the business needs next, FOUND. can support ongoing Local SEO, Google Business optimisation, analytics and reporting, paid acquisition, automation, content and selected integrations. These services are scoped separately from the website packages."],
  ["Can I cancel the monthly plan?", "Cancellation terms, notice periods and any transition work are stated clearly in the service agreement before the project begins."],
  ["What is not included as a minor update?", "New pages, new systems, full redesigns, new integrations, large content uploads and custom development are quoted separately."],
] as const;
