export const faqs = [
  ["How much does a website cost?", "Our current packages start at €690 setup plus €59 per month. The right package depends on page count, integrations, content and the role the website plays in your business."],
  ["How long does a website take?", "A focused small business website usually takes a few weeks once content and feedback are supplied. More complex sites take longer. Your proposal will include a realistic schedule."],
  ["How do payments work?", "The standard process is 50% to begin and 50% before launch. Monthly care starts when the site goes live."],
  ["Will I own my website?", "Yes. Ownership and access are documented in the proposal. Any licensed third-party tools remain subject to their own terms."],
  ["Can you work with my current domain?", "Yes. We can connect an existing domain and help coordinate DNS changes without unnecessarily disrupting email or other services."],
  ["Do you provide hosting?", "Yes. Hosting, SSL, monitoring and backups are included in the monthly packages shown on the pricing page."],
  ["What does maintenance include?", "Maintenance covers hosting, monitoring, technical updates, backups and the monthly allowance for minor text, image, contact-detail or opening-hour changes."],
  ["Does unused maintenance time roll over?", "No. Monthly maintenance time is reserved capacity for that month and does not roll over."],
  ["Do you guarantee first place on Google?", "No responsible provider can guarantee a ranking. We build a sound SEO foundation and improve relevance, quality and visibility over time."],
  ["Can you write the website content?", "All packages include content structure and guidance. Growth includes copywriting assistance. Full or specialist copywriting can be quoted separately."],
  ["What about photography and video?", "We can work with your existing assets, recommend a shoot or coordinate professional photography and videography as an add-on."],
  ["How many revisions are included?", "The proposal defines clear feedback stages. We aim to align direction early so revisions remain focused and productive."],
  ["Can the website be in Greek and English?", "Yes. Premium includes bilingual capability. Translation and content entry scope depend on the amount and condition of the supplied content."],
  ["Will I see calls and enquiries in analytics?", "Yes. Where consent and technology allow, we track meaningful actions such as phone, WhatsApp, email, booking and form interactions."],
  ["Can you connect a booking system?", "Yes. We can connect an existing booking platform or scope a more advanced booking workflow as an add-on."],
  ["Can you redesign my existing website?", "Yes. We can audit the current site, retain what is useful and rebuild the experience around clearer goals."],
  ["Do you build e-commerce websites?", "E-commerce can be scoped separately. The packages shown focus on lead-generating local business websites."],
  ["What happens after launch?", "We monitor the technical foundation, handle included minor updates and can continue with SEO, ads, automation, content and conversion improvements."],
  ["Can I cancel the monthly plan?", "Cancellation terms, notice periods and any transition work are stated clearly in the service agreement before the project begins."],
  ["What is not included as a minor update?", "New pages, new systems, full redesigns, new integrations, large content uploads and custom development are quoted separately."],
] as const;
